apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-one
  template:
    metadata:
      labels:
        app: service-one
    spec:
      containers:
      - image: svc-1:v1
        imagePullPolicy: IfNotPresent
        name: service-one